import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button } from "react-daisyui";

const DonePage: NextPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Done</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-6 items-center justify-center min-h-screen p-4">
        <h3 className="text-xl">Speed Dating Done</h3>

        <Button onClick={() => router.push("/waiting")}>
          Go to Waiting Room
        </Button>
      </main>
    </>
  );
};

export default DonePage;
