import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Button, Input, Form } from "react-daisyui";
import { useForm } from "react-hook-form";
import { trpc } from "../utils/trpc";

type RegisterForm = {
  name: string;
  contactInfo: string;
};

const Home: NextPage = () => {
  const createUser = trpc.useMutation("users.createUser");
  const router = useRouter();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterForm>();

  const onSubmit = async (data: RegisterForm) => {
    const newUser = await createUser.mutateAsync(data);
    router.push("/waiting");
  };

  return (
    <>
      <Head>
        <title>Speed Date</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-6 items-center justify-center min-h-screen p-4">
        <h3 className="text-xl">Join a Speed Dating Session</h3>

        <Form
          onSubmit={handleSubmit(onSubmit)}
          className="w-1/3 flex flex-col gap-4"
        >
          <div>
            <Form.Label title="Name"></Form.Label>
            <Input
              {...register("name", { required: true })}
              className="w-full"
              placeholder="your display name"
            />
            {errors.name && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>

          <div>
            <Form.Label title="Contact Info"></Form.Label>
            <Input
              {...register("contactInfo", { required: true })}
              className="w-full"
              placeholder="fb link, whatsapp number, email, etc."
            />
            {errors.contactInfo && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>

          <Button type="submit" color="primary">
            Join Session
          </Button>
        </Form>
      </main>
    </>
  );
};

export default Home;
