import type { NextPage } from "next";
import Head from "next/head";

const WaitingPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Waiting for Users</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-6 items-center justify-center min-h-screen p-4">
        <h3 className="text-xl">Waiting for Users to Connect With...</h3>
      </main>
    </>
  );
};

export default WaitingPage;
